version: "3.7"
services:
    app:
        build:
            context: ../..
            dockerfile: ./docker/dev/Dockerfile
        command: /start_reload.sh
        ports:
            - "80:80"
            - "3000:3000"
        volumes:
            - ../../:/app:cached
        depends_on:
            - pg
        env_file:
            - ./env/env-core.env
            - ./env/env-db.env
            - ./env/env-email.env
            - ./env/env-ext.env
            - ./env/env-social.env
    pg:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - ../../_tmp/db/pg:/var/lib/postgresql/data
        env_file:
            - ./env/env-db.env
    pgadmin:
        image: dpage/pgadmin4
        # logging:
            # driver: none
        restart: always
        ports:
            - "5052:5052"
        volumes:
            - ../../_tmp/db/pgadmin:/var/lib/pgadmin
        depends_on:
            - pg
        env_file:
            - ./env/env-db.env