# docker compose -p fastapi-beanie-poc -f docker/compose.yml build
# docker compose -p fastapi-beanie-poc -f docker/compose.yml up
# docker compose -p fastapi-beanie-poc -f docker/compose.yml down

services:

  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ["uvicorn", "--reload", "--reload-dir", "./app", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ../:/app:cached
    env_file:
      - ./env/api.env
      - ./env/db.env
    depends_on:
      - db
      - cache

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../_data/db:/data/db
    env_file:
      - ./env/db.env

  cache:
    image: redis
    restart: always
    command:
      - /bin/sh
      - -c
      - redis-server --save 60 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
      # - redis-server --save 60 1 --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
      # - redis-server --save 60 1 --loglevel debug
    ports:
      - "6379:6379"
    volumes:
      - ../_data/cache:/data
    env_file:
      - ./env/db.env

  db-admin:
    profiles:
      - debug
    image: mongo-express
    restart: always
    ports:
      - "8001:8081"
    env_file:
      - ./env/db.env
    depends_on:
      - db

  cache-admin:
    profiles:
      - debug
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8002:8081"
    env_file:
      - ./env/db.env
    depends_on:
      - cache

  sonar:
    profiles:
      - sonar
    image: sonarqube:community
    ports:
      - "8003:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    env_file:
      - ./env/sonar.env
    depends_on:
      - sonar-db

  sonar-db:
    profiles:
      - sonar
    image: postgres
    volumes:
      - ../_data/sonar-db:/var/lib/postgresql/data
    env_file:
      - ./env/sonar.env

  sonar-scanner:
    profiles:
      - sonar-scanner
    image: sonarsource/sonar-scanner-cli
    volumes:
      - ../api:/usr/src
    depends_on:
      - sonar

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: