# docker compose -p fastapi-template -f docker/compose.yml build
# docker compose -p fastapi-template -f docker/compose.yml up
# docker compose -p fastapi-template -f docker/compose.yml down

services:

  api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.api
      target: dev
    command: ["sh", "run-dev.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ../api:/app/api:cached
    env_file:
      - ./env/api.env
      - ./env/db.env
    depends_on:
      - db
      - cache

  db:
    image: mongo
    restart: always
    volumes:
      - db_data:/data/db
    env_file:
      - ./env/db.env

  cache:
    image: redis
    restart: always
    command:
      - /bin/sh
      - -c
      - redis-server --save 60 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - cache_data:/data
    env_file:
      - ./env/db.env

  ui:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.ui
    command: ["sh", "run-dev.sh"]
    ports:
      - "8001:3000"
    volumes:
      - ../ui:/app/ui:cached

  db-admin:
    profiles:
      - debug
    image: mongo-express
    restart: always
    ports:
      - "8010:8081"
    env_file:
      - ./env/db.env
    depends_on:
      - db

  cache-admin:
    profiles:
      - debug
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8011:8081"
    env_file:
      - ./env/db.env
    depends_on:
      - cache

  sonar:
    profiles:
      - sonar
    # image: sonarqube:community
    build:
      context: .
      dockerfile: ./Dockerfile.sonar-arm64
    ports:
      - "8020:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    env_file:
      - ./env/sonar.env
    depends_on:
      - sonar-db

  sonar-db:
    profiles:
      - sonar
    image: postgres
    volumes:
      - sonar-db_data:/var/lib/postgresql/data
    env_file:
      - ./env/sonar.env

  sonar-scanner:
    profiles:
      - sonar-scanner
    # image: sonarsource/sonar-scanner-cli
    build:
      context: .
      dockerfile: ./Dockerfile.sonar-scanner-arm64
    env_file:
      - ./env/sonar-scanner.env
    volumes:
      - ../api:/usr/src
    depends_on:
      - sonar

  jenkins:
    profiles:
      - ci
    image: jenkins/jenkins:lts
    ports:
      - "8021:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-ssh:
    profiles:
      - ci
    image: jenkins/ssh-agent
    env_file:
      - ./env/jenkins.env

volumes:
  db_data:
  cache_data:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  sonar-db_data:
  jenkins_home:
