# docker build --target base -t fastapi-template/ui -f docker/Dockerfile.ui .
# docker run -d --name fastapi-template-ui -p 8001:3000 fastapi-template/ui
# docker start fastapi-template-ui
# docker stop fastapi-template-ui
# docker rm fastapi-template-ui
# docker exec -it fastapi-template-ui bash

FROM node:lts-bookworm-slim as base

WORKDIR /app/ui

COPY ./ui/app ./app

WORKDIR /app/ui/app

RUN npm install
RUN npm run build

EXPOSE 3000
CMD ["sh", "run-prod.sh"]
