# docker build . -t api-template/test -f docker/test_Dockerfile
# docker run api-template/test

FROM python:3.9-slim-bullseye

WORKDIR /app/api

COPY ./api/requirements/api_requirements.txt ./requirements/

RUN pip install -r requirements/api_requirements.txt

COPY ./api/requirements/dev_requirements.txt ./requirements/

RUN pip install -r requirements/dev_requirements.txt

COPY ./api/app ./app

CMD ["pdoc", "--html", "--output-dir", "docs", "app"]
# CMD ["sleep", "infinity"]