# docker build --target base -t fastapi-template/api -f docker/Dockerfile.api .
# docker run -d --name fastapi-template-api -p 8000:8000 --env-file docker/env/api.env --env-file docker/env/db.env fastapi-template/api
# docker start fastapi-template-api
# docker stop fastapi-template-api
# docker rm fastapi-template-api
# docker exec -it fastapi-template-api bash

FROM python:3.12-slim-bookworm as base

WORKDIR /app/api

COPY ./api/requirements/requirements_api.txt ./requirements/
RUN pip install -r requirements/requirements_api.txt

COPY ./api/app ./app
EXPOSE 8000
CMD ["sh", "run-prod.sh"]


FROM base as dev

RUN apt update
RUN apt install -y gcc python3-dev

COPY ./api/requirements/requirements_test.txt ./requirements/
RUN pip install -r requirements/requirements_test.txt

COPY ./api/requirements/requirements_dev.txt ./requirements/
RUN pip install -r requirements/requirements_dev.txt
