[tool.pylint.format]
max-line-length=88

[tool.pylint.messages_control]
disable=[
  "invalid-name",
  "logging-fstring-interpolation",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "no-member",
  "redefined-outer-name"
]

[tool.pylint.reports]
output-format="text"